verbose: false
reporting:
    print: summary
    reports:
        - html
    dir: ./docs
    default-excludes: true
    excludes: ["**/**/*.spec.js",]
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
hooks:
    hook-run-in-context: false
    post-require-hook: null
